ALTER TABLE projects ADD COLUMN walls TEXT DEFAULT '[]';
ALTER TABLE projects ADD COLUMN doors TEXT DEFAULT '[]';
ALTER TABLE projects ADD COLUMN windows TEXT DEFAULT '[]';
ALTER TABLE projects ADD COLUMN updated_at TIMESTAMP DEFAULT NULL;